# This file defines a function which returns a list of emacs packages.
# It is the only source of packages for ~/.emacs.d, which doesn't use package.el.
epkgs:
with epkgs; [
  all-the-icons
  apheleia
  auctex
  corfu
  csharp-mode
  dashboard
  doom-modeline
  flycheck
  flycheck-swift
  fsharp-mode
  fzf
  go-mode
  haskell-mode
  js2-mode
  latex-preview-pane
  ligature
  lsp-haskell
  lsp-mode
  lsp-treemacs
  lsp-ui
  magit
  nix-mode
  ob-swiftui
  org
  org-bullets
  org-preview-html
  org-roam
  org-variable-pitch
  page-break-lines
  projectile
  python-mode
  racket-mode
  rainbow-delimiters
  rustic
  slime
  swift-mode
  treemacs
  treemacs-all-the-icons
  treemacs-magit
  typescript-mode
  vterm
  web-mode
  zig-mode
]
